### ISSUE TITLE
2-ui/2-events/05-dispatch-events/article.md and 

### ISSUE THREAD

**Issue by leviding** [xitu/javascript-tutorial-zh#159]
* Markdown 文件：
    * [2-ui/2-events/05-dispatch-events/article.md](https://github.com/xitu/javascript-tutorial-zh/blob/zh-hans/2-ui/2-events/05-dispatch-events/article.md)
    * [2-ui/2-events/index.md](https://github.com/xitu/javascript-tutorial-zh/blob/zh-hans/2-ui/2-events/index.md)
  * PR 地址：#162
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有 MarkDown 文件
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：4.5-5.5 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
@leviding  翻译认领

**Comment by leviding** [comment]
@Starriers ok

**Comment by xutaogit** [comment]
校对认领
