### ISSUE TITLE
Publishing preparations

### ISSUE THREAD

**Issue by iliakan** [xitu/javascript-tutorial-zh#164]
1. Guess, there's no need in https://github.com/iliakan/javascript-tutorial-cn.
So I can remove it, and this repo/zh-hans will be the source branch for translation, ok?

2. Please see how the tutorial looks in https://github.com/iliakan/javascript-tutorial-server
The first part is complete and ready for publishing?

**Comment by leviding** [comment]
@iliakan The first part is complete and ready for publishing now.

**Comment by iliakan** [comment]
Great, we'll get down to publishing it.

**Comment by iliakan** [comment]
I'm doing that yet. Design and additional translation issues.

**Comment by iliakan** [comment]
Actually, almost done, but need to test on English first. 
Refactored site engine, all new modules etc.

**Comment by leviding** [comment]
@iliakan Get it！

**Comment by iliakan** [comment]
Sorry for the delay, it occured that a refactoring would be really helpful, so I put a lot of time to do it right.

**Comment by iliakan** [comment]
Please fork the server code https://github.com/iliakan/javascript-tutorial-server

That's the engine code, it contains messages for site navigation etc.

Find all files named `en.yml`, copy them to `zh.yml` and translate into Chinese.

**Comment by iliakan** [comment]
And then we'll be able to publish it.

**Comment by leviding** [comment]
@iliakan OK

**Comment by leviding** [comment]
@iliakan The translation has been done.

**Comment by iliakan** [comment]
@leviding after a period of inactivity WeChat wants someone to verify my identity. Could you please remind your wechat mobile number? If it's confidential, iliakan@gmail.com.

**Comment by leviding** [comment]
@iliakan 17612736233

**Comment by iliakan** [comment]
Please open WeChat, search "WeChat Team", and confirm my request in the WeChat Team -> Account -> Assistant Verification.

**Comment by iliakan** [comment]
I tried entering your WeChat twice. Both times the request expires with time, as you do not approve it.

Maybe you have another contact, like Telegram/Skype?

**Comment by leviding** [comment]
@iliakan My telegram account https://t.me/leviding

**Comment by iliakan** [comment]
@leviding we updated /ebook design, please translate some new phrases in modules/ebook/locales/zh.yml, javascript-nodejs repo.

**Comment by leviding** [comment]
@iliakan DONE

**Comment by iliakan** [comment]
Thank you!

**Comment by leviding** [comment]
@iliakan All of the content have been translated into Chinese.

**Comment by iliakan** [comment]
Wow! That's just cool. 
My counter shows about 90%, probably because of renaming some stuff?

**Comment by leviding** [comment]
Maybe it is. The translation has been done.

**Comment by iliakan** [comment]
Please publish the information about the site somewhere in Chinese sources. 
Few people know about it yet =(
