### ISSUE TITLE
2-ui/4-forms-controls/1-form-elements, 2-ui/4-forms-controls/index.md and 2-ui/index.md

### ISSUE THREAD

**Issue by leviding** [xitu/javascript-tutorial-zh#187]
* Markdown 文件：
    * [2-ui/4-forms-controls/1-form-elements](https://github.com/xitu/javascript-tutorial-zh/tree/zh-hans/2-ui/4-forms-controls/1-form-elements)
    * [2-ui/4-forms-controls/index.md](https://github.com/xitu/javascript-tutorial-zh/blob/zh-hans/2-ui/4-forms-controls/index.md)
    * [2-ui/index.md](https://github.com/xitu/javascript-tutorial-zh/blob/zh-hans/2-ui/index.md)
  * PR 地址：https://github.com/xitu/javascript-tutorial-zh/pull/207
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有 MarkDown 文件
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4-5 分
  * 校对积分：0.5-2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by steinliber** [comment]
翻译认领

**Comment by leviding** [comment]
@steinliber ok

**Comment by leviding** [comment]
@steinliber 这篇翻译的怎么样啦

**Comment by steinliber** [comment]
已经提交了

**Comment by steinliber** [comment]
https://github.com/xitu/javascript-tutorial-zh/pull/207
