### ISSUE TITLE
contributors.md, LICENSE.md and README.md

### ISSUE THREAD

**Issue by leviding** [xitu/javascript-tutorial-zh#190]
* Markdown 文件：
    * [contributors.md](https://github.com/xitu/javascript-tutorial-zh/blob/zh-hans/contributors.md)
    * [LICENSE.md](https://github.com/xitu/javascript-tutorial-zh/blob/zh-hans/LICENSE.md)
    * [README.md](https://github.com/xitu/javascript-tutorial-zh/blob/zh-hans/README.md)
  * PR 地址：https://github.com/xitu/javascript-tutorial-zh/pull/210
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有 MarkDown 文件
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：0.5-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lihanxiang** [comment]
翻译认领的 @leviding
