### ISSUE TITLE
5-regular-expressions/12-regexp-anchors, 3-regexp-multiline-mode/article.md, 14-regexp-lookahead/article.md and 5-regular-expressions/index.md

### ISSUE THREAD

**Issue by leviding** [xitu/javascript-tutorial-zh#240]
* Markdown 文件：
    * [5-regular-expressions/12-regexp-anchors](https://github.com/xitu/javascript-tutorial-zh/tree/zh-hans/5-regular-expressions/12-regexp-anchors)
    * [13-regexp-multiline-mode/article.md](https://github.com/xitu/javascript-tutorial-zh/blob/zh-hans/5-regular-expressions/13-regexp-multiline-mode/article.md)
    * [14-regexp-lookahead/article.md](https://github.com/xitu/javascript-tutorial-zh/blob/zh-hans/5-regular-expressions/14-regexp-lookahead/article.md)
    * [5-regular-expressions/index.md](https://github.com/xitu/javascript-tutorial-zh/blob/zh-hans/5-regular-expressions/index.md)
  * PR 地址：https://github.com/xitu/javascript-tutorial-zh/pull/266
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有 MarkDown 文件
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：4-5 分
  * 校对积分：1.5-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lcx-seima** [comment]
@leviding 后两个MD怎么是空的？
14-regexp-lookahead/article.md
5-regular-expressions/index.md

**Comment by leviding** [comment]
@lcx-seima 不是空的吧，有两行内容，能翻译的翻译一下，固定属于或专有名词保留不译

**Comment by CoderMing** [comment]
@leviding 翻译认领

**Comment by leviding** [comment]
@CoderMing 👍
