### ISSUE TITLE
06-events-and-timing-in-depth/article.md and archive/2-eval-calculator-errors 含俄语部分

### ISSUE THREAD

**Issue by leviding** [xitu/javascript-tutorial-zh#245]
* Markdown 文件：
    * [06-events-and-timing-in-depth/article.md](https://github.com/xitu/javascript-tutorial-zh/blob/zh-hans/archive/06-events-and-timing-in-depth/article.md)
    * [archive/2-eval-calculator-errors](https://github.com/xitu/javascript-tutorial-zh/tree/zh-hans/archive/2-eval-calculator-errors)
  * PR 地址：https://github.com/xitu/javascript-tutorial-zh/pull/252
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有 MarkDown 文件
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：1.5-3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ThomasWhyne** [comment]
@leviding  翻译认领 俄语部分可以不翻译吗？

**Comment by leviding** [comment]
@ThomasWhyne 俄语部分保留不动
