### ISSUE TITLE
为什么进度从80%，变成现在的60%？

### ISSUE THREAD

**Issue by Mrjianghan** [xitu/javascript-tutorial-zh#318]

**Comment by ish-kafel** [comment]
因为英文版作者新加入很多内容，而中文版更新不及时，所以整体比例下降了

**Comment by Mrjianghan** [comment]
> 因为英文版作者新加入很多内容，而中文版更新不及时，所以整体比例下降了

那我的离线版是买早了。。。。。

**Comment by ish-kafel** [comment]
> > 因为英文版作者新加入很多内容，而中文版更新不及时，所以整体比例下降了
> 
> 那我的离线版是买早了。。。。。
emm我这些天抽空再翻译一部分吧，总之大家一起翻译加上校对速度就能跟上了
